// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamPlaytimeViewer.Data;

#nullable disable

namespace SteamPlaytimeViewer.Migrations
{
    [DbContext(typeof(SteamDbContext))]
    partial class SteamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SteamPlaytimeViewer.Models.Game", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAchievements")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SteamPlaytimeViewer.Models.User", b =>
                {
                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SteamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SteamPlaytimeViewer.Models.UserGameStats", b =>
                {
                    b.Property<string>("UserSteamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameAppId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstPlayed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<double>("PlaytimeHours")
                        .HasColumnType("REAL");

                    b.Property<int>("UnlockedAchievements")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSteamId", "GameAppId");

                    b.HasIndex("GameAppId");

                    b.ToTable("UserGameStats");
                });

            modelBuilder.Entity("SteamPlaytimeViewer.Models.UserGameStats", b =>
                {
                    b.HasOne("SteamPlaytimeViewer.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SteamPlaytimeViewer.Models.User", "User")
                        .WithMany("GameStats")
                        .HasForeignKey("UserSteamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SteamPlaytimeViewer.Models.User", b =>
                {
                    b.Navigation("GameStats");
                });
#pragma warning restore 612, 618
        }
    }
}
